import mongoose, { type HydratedDocument, type InferSchemaType, type Model } from "mongoose";

export const MAX_CATEGORY_LEN = 128;
/** Max distinct categories stored per user + API key document. */
export const MAX_CATEGORIES = 50;
/** Max HTTPS (or localhost http) origins allowed to parent-frame the public embed. */
export const MAX_EMBED_ALLOWED_ORIGINS = 20;

export const MAX_EMBED_ASSISTANT_NAME_LEN = 80;
export const MAX_EMBED_ASSISTANT_DESCRIPTION_LEN = 2000;
export const MAX_EMBED_ASSISTANT_GREETING_LEN = 1000;
export const MAX_EMBED_COLOR_LEN = 12;
export const MAX_EMBED_AI_DISCLAIMER_LEN = 500;
export const MAX_EMBED_FURTHER_INFO_LABEL_LEN = 80;
export const MAX_EMBED_FURTHER_INFO_URL_LEN = 2048;
export const MAX_EMBED_APP_BADGE_LABEL_LEN = 80;

/** Shown on the public embed when `embedInfo.aiDisclaimer` is unset. */
export const DEFAULT_EMBED_AI_DISCLAIMER =
  "Responses are generated by AI and may be inaccurate. Verify important details with official sources.";

/** Default app badge label for Pro and Scale when no custom label is set. */
export const DEFAULT_APP_BADGE_LABEL = "Provided by SapAi";

const HEX_COLOR_RE = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/;

const appBadgeSchema = new mongoose.Schema(
  {
    enabled: { type: Boolean, default: true },
    label: { type: String, default: null, maxlength: MAX_EMBED_APP_BADGE_LABEL_LEN },
  },
  { _id: false },
);

const furtherInfoLinkSchema = new mongoose.Schema(
  {
    label: { type: String, default: null, maxlength: MAX_EMBED_FURTHER_INFO_LABEL_LEN },
    url: { type: String, default: null, maxlength: MAX_EMBED_FURTHER_INFO_URL_LEN },
  },
  { _id: false },
);

const embedInfoSchema = new mongoose.Schema(
  {
    assistantName: { type: String, default: null, maxlength: MAX_EMBED_ASSISTANT_NAME_LEN },
    assistantProfilePicture: {
      fileId: { type: String, default: null },
      url: { type: String, default: null },
    },
    assistantDescription: { type: String, default: null, maxlength: MAX_EMBED_ASSISTANT_DESCRIPTION_LEN },
    assistantGreeting: { type: String, default: null, maxlength: MAX_EMBED_ASSISTANT_GREETING_LEN },
    embedColor: {
      type: String,
      default: null,
      maxlength: MAX_EMBED_COLOR_LEN,
      validate: {
        validator(v: unknown) {
          if (v == null || v === "") return true;
          return typeof v === "string" && HEX_COLOR_RE.test(v);
        },
        message: "embedColor must be null or a hex color (#RGB, #RRGGBB, or #RRGGBBAA).",
      },
    },
    /** Optional custom AI disclaimer; null uses {@link DEFAULT_EMBED_AI_DISCLAIMER} in the widget. */
    aiDisclaimer: { type: String, default: null, maxlength: MAX_EMBED_AI_DISCLAIMER_LEN },
    /** One optional link (WhatsApp, website, Linktree, etc.) with a custom label. */
    furtherInfoLink: { type: furtherInfoLinkSchema, default: undefined },
    /** Plan-governed SapAi branding badge (Scale may disable or customize label). */
    appBadge: { type: appBadgeSchema, default: undefined },
  },
  { _id: false },
);

/**
 * Per–API-key FAQ taxonomy: **categories** grow when users upload PDFs / admin adds labels.
 * Embed security fields live on the document root (indexes, auth queries). Branding lives in `embedInfo`.
 */
const faqConstantSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    apiKeyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ApiKey",
      required: true,
      index: true,
    },
    /** Dynamic labels (e.g. `sample_preparation`, `shipping`). Deduped, trimmed on save. */
    categories: {
      type: [String],
      default: [],
      validate: {
        validator(v: unknown) {
          return Array.isArray(v) && v.length <= MAX_CATEGORIES;
        },
        message: `At most ${MAX_CATEGORIES} categories.`,
      },
    },

    embedEnabled: { type: Boolean, default: false, index: true },
    /** @deprecated Legacy plaintext; new tokens use embedTokenHash only. */
    embedToken: { type: String, default: null, maxlength: 160 },
    embedTokenHash: { type: String, default: null, maxlength: 64 },
    embedTokenCreatedAt: { type: Date, default: null },
    embedAllowedOrigins: {
      type: [String],
      default: [],
      validate: {
        validator(v: unknown) {
          return Array.isArray(v) && v.length <= MAX_EMBED_ALLOWED_ORIGINS;
        },
        message: `At most ${MAX_EMBED_ALLOWED_ORIGINS} embed allowed origins.`,
      },
    },

    embedInfo: { type: embedInfoSchema, default: undefined },
  },
  { timestamps: true, collection: "faqconstants" },
);

faqConstantSchema.index({ userId: 1, apiKeyId: 1 }, { unique: true });
faqConstantSchema.index({ embedToken: 1 }, { unique: true, sparse: true });
faqConstantSchema.index({ embedTokenHash: 1 }, { unique: true, sparse: true });

faqConstantSchema.pre("save", function normalizeCategories(next) {
  const raw = this.categories as string[] | undefined;
  if (!raw?.length) {
    this.set("categories", []);
    next();
    return;
  }
  const seen = new Set<string>();
  const out: string[] = [];
  for (const s of raw) {
    const t = typeof s === "string" ? s.trim().slice(0, MAX_CATEGORY_LEN) : "";
    if (!t || seen.has(t)) continue;
    seen.add(t);
    out.push(t);
  }
  this.set("categories", out);
  next();
});

export type FaqConstantLean = InferSchemaType<typeof faqConstantSchema>;
export type FaqConstantDocument = HydratedDocument<FaqConstantLean>;

export const FaqConstantModel: Model<FaqConstantLean> =
  mongoose.models.FaqConstant || mongoose.model<FaqConstantLean>("FaqConstant", faqConstantSchema);
